## NUMÈRICA

## TRIU subs endarrera
* Elements diagonals differents de 0
* determinant diferent de 0

In [ ]:
# TRIU. matrius triangulars superiors
import numpy as np

def triU(U, b, tol=1e-10):
    n = len(U)
    x = b

    for i in range(n-1, -1, -1):
        if (abs(U[i][i]) < tol):
            raise ValueError("Element diagonal massa petit!")
        x[i] = b[i]
        for j in range(i+1, n):
            x[i] -= U[i][j] * x[j]
        x[i] /= U[i][i]

    return x


A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
b = np.array([14, 23, 18])
print(triU(A, b))

[1 2 3]


## TRIL subs endavant
* Elements diagonals differents de 0
* determinant diferent de 0

In [ ]:
# matrius triangulars inferiors
def triL(L, b, tol=1e-10):
    n = len(L)
    x = b

    for i in range(0, n):
        if (abs(L[i][i]) < tol):
            raise ValueError("Element diagonal massa petit!")
        x[i] = b[i]
        for j in range(0, i):
            x[i] -= L[i][j] * x[j]
        x[i] /= L[i][i]

    return x

def triL_uns_diagonal(L, b, tol=1e-10):
    n = len(L)
    x = b

    for i in range(0, n):
        if (abs(L[i][i]) < tol):
             raise ValueError("Element diagonal massa petit!")
        x[i] = b[i]
        for j in range(0, i):
            x[i] -= L[i][j] * x[j]
        # x[i] /= L[i][i] suposo uns a la diagonal

    return x

A = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
b = np.array([1, 2, 3])

print(triL(A, b))

[1 0 0]


## GAUSS SENSE PIVOTATGE
* O matrius simètriques definides positives
* O matrius edd
* O matriu regular i elements diagonal diferents de zero

In [ ]:
def elimGaussresolucio(A, b, tol=1.e-10):
    n = len(A)

    for k in range(n-1):
        for i in range(k+1, n):
            m = A.copy()
            if (abs(A[k][k]) < tol):
                raise ValueError("Element diagonal massa petit!")
            m[i][k] = A[i][k]/A[k][k]
            b[i] = b[i] - m[i][k] * b[k]
            for j in range(k+1, n):  # canviar k+1 per que surti triangular
                A[i][j] = A[i][j] - m[i][k] * A[k][j]

    x = triU(A, b)
    return x
    #return m, b


A = np.array([[1, 5, 2], [2, 1, 7], [3, 4, 1]], dtype=np.float64)
b = np.array([1, 2, 3], dtype=np.float64)
print(elimGaussresolucio(A, b))
A = np.array([[1, 5, 2], [2, 1, 7], [3, 4, 1]], dtype=np.float64)
b = np.array([1, 2, 3], dtype=np.float64)
print(np.linalg.solve(A, b))

[ 1. -0. -0.]
[1. 0. 0.]


## fact LU
* elements diagonals diferents de 0

In [ ]:
def factLU(a, tol=1.e-10):
    n = len(a)

    for k in range(n):
        for i in range(k+1, n):
            m = a
            if (abs(a[k][k]) < tol):
                raise ValueError("Element diagonal massa petit!")
            m[i][k] = a[i][k] / a[k][k]
            for j in range(k+1, n):  # canviar k+1 per que surti triangular
                a[i][j] = a[i][j] - m[i][k] * a[k][j]

            a[i][k] = m[i][k]

    return a

M = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)
A = factLU(M) # retorna una matriu L + U - Id

L = np.tril(A, -1) + np.eye(3)
U = np.triu(A)

print(L@U)

# calcul inversa al docs 2b -----------------------------------------------------------
M = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)
A = factLU(M)

L = np.tril(A, -1) + np.eye(3)
U = np.triu(A)

#print(L)
#print(U)

n = len(A)

def inversaLU(A): # A = LU
    ans = A.copy()

    for i in range(n):
        b = np.zeros(n, dtype = np.float64)
        b[i] = 1
        Y = triL_uns_diagonal(A, b)
        X = triU(A, Y)
        ans[:, i] = X
    return ans

print(inversaLU(A))

########### test
print()
M = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)
print(np.linalg.inv(M))

[[1. 1. 0.]
 [2. 0. 2.]
 [0. 3. 3.]]
[[ 0.5         0.25       -0.16666667]
 [ 0.5        -0.25        0.16666667]
 [-0.5         0.25        0.16666667]]

[[ 0.5         0.25       -0.16666667]
 [ 0.5        -0.25        0.16666667]
 [-0.5         0.25        0.16666667]]


## doodlittle
* elements diagonals de la U diferents de 0

In [ ]:
def doolittle(A, tol=1.e-10):
    n = len(A)
    U = A.copy()
    L = A.copy()

    for k in range(n):
        for j in range(k, n):
            U[k, j] = A[k, j]
            for r in range(0, k):
                U[k, j] = U[k, j]- L[k, r]*U[r, j]
        L[k, k] = 1
        for  i in range(k+1, n):
            L[k, k] = A[i, k]
            for  r in range(0, k):
                L[i, k] = L[i, k] - L[i, r]*U[r, k]
        if (abs(U[k][k]) < tol):
            raise ValueError("Element diagonal massa petit!")
        L[i, k] = L[i, k] / U[k, k]

    return U, L

A = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)

U1, L1 = doolittle(A)
#print(U1)
#print(L1)

L = np.tril(L1, -1) + np.eye(3)
U = np.triu(U1)

print(L@U)
print(L + U - np.eye(3))

[[1. 1. 0.]
 [2. 0. 2.]
 [0. 3. 3.]]
[[ 1.   1.   0. ]
 [ 2.  -2.   2. ]
 [ 0.  -1.5  6. ]]


## PA = LU pivotatge parcial
* per sistemes mal condicionats pot donar error
* no tenim requisits, per això fem pivotatge

In [ ]:
def factPALU(A, tol=1.e-10):
    n = len(A)
    p = np.zeros(n)
    for k in range(0, n):
        p[k] = k

    for k in range(0, n):
        i1 = k
        s = A[k][k]
        for i in range(k+1, n):
            if abs(A[i][k] > s):
                i1 = i
                s = abs(A[i][k])

        for j in range(0, n):
            s = A[i1][j]
            A[i1][j] = A[k][j]
            A[k][j] = s

        r = p[i1]
        p[i1] = p[k]
        p[k] = r

        if (abs(A[k][k]) < tol):
            raise ValueError("Element diagonal massa petit!")

        for i in range(k+1, n):  # canviar k+1 per que surti triangular
            m = A[i][k]/A[k][k]
            A[i][k] = m
            for j in range(k+1, n):
                A[i][j] -= m*A[k][j]

    return A, p

M = np.array([[0,1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1], [1, 2, 3, 0]], dtype = np.float64)
n = len(M)
A, p = factPALU(M) # la matriu A la desglocem en L i U, i p les permutacions

L = np.tril(A, -1) + np.eye(4)
U = np.triu(A)

#print(p)
# p es per files i A = L + U -Id
# p = (1, 2, 3, 0) vol dir uns a les posicions
P = np.zeros((n, n))
for i in range(n):
    P[i,int(p[i])] = 1

M = np.array([[0,1, 2, 3], [3, 0, 1, 2], [2, 3, 0, 1], [1, 2, 3, 0]], dtype = np.float64)
print(P@M)
print(L@U)

[[3. 0. 1. 2.]
 [2. 3. 0. 1.]
 [1. 2. 3. 0.]
 [0. 1. 2. 3.]]
[[3. 0. 1. 2.]
 [2. 3. 0. 1.]
 [1. 2. 3. 0.]
 [0. 1. 2. 3.]]


## PA = LU pivotatge parcial esglaonat

In [ ]:
def pivotatge_parcial_esglaonat(a, tol=1.e-10):
    n = len(a)
    p = np.zeros(n)
    npermutacions = 0 # calcular determinant

    for k in range(0, n):
        p[k] = k

    for k in range(0, n):

        vmax = np.zeros(n)
        for q in range(n):
            for w in range(n):
                vmax[q] = max(abs(vmax[q]), abs(a[q][w]))

            vmax[q] = abs(a[q][k] / vmax[q])

        #print(vmax)

        i1 = k
        s = a[k][k]
        for i in range(k+1, n):
            if abs(a[i][k] > s):
                i1 = i
                s = abs(a[i][k])

        for j in range(0, n):
            s = a[i1][j]
            a[i1][j] = a[k][j]
            a[k][j] = s

        r = p[i1]
        p[i1] = p[k]
        p[k] = r

        npermutacions += 1 # calcular determinant

        for i in range(k+1, n):  # canviar k+1 per que surti triangular
            m = a[i][k]/a[k][k]
            a[i][k] = m
            for j in range(k+1, n):
                a[i][j] -= m*a[k][j]

    return a, p, npermutacions

#########
M = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype = np.float64)
A, p, npermutacions = pivotatge_parcial_esglaonat(M)
# print(A, p)
L = np.tril(A, -1) + np.eye(4)
U = np.triu(A)

P = np.zeros((n, n))
for i in range(n):
    P[i,int(p[i])] = 1

M = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype = np.float64)
print(P@M-L@U)

################
print("determinant de A: ", np.linalg.det(P)*np.linalg.det(U))
# determinant d'U es el producte d'elements de la diagonal i el det de p es -1^q
# on q es el num de canvis de fila de P

detU = 1
for i in range(n):
    detU *= U[i][i]
print((-1)**npermutacions*detU)

##################### calcular inversa
print()

M = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype = np.float64)
A, p, npermutacions = pivotatge_parcial_esglaonat(M)
L = np.tril(A, -1) + np.eye(4)
U = np.triu(A)

def inversa(P, L, U):
    n = len(P)
    invA = np.zeros((n, n))
    for k in range(0, n):
        b = P[:,k]
        y = triL_uns_diagonal(L, b)
        invA[:,k] = triU(U,y)
    return invA

print(inversa(P, L, U))
M = np.array([[1, 2, 2, 4], [1, 2, 1, 2], [3, 2, 0, 6], [4, 2, 1, 1]], dtype = np.float64)
print(np.linalg.inv(M))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
determinant de A:  40.0
40.0

[[ 0.05  -0.4    0.05   0.3  ]
 [-0.525  1.2   -0.025 -0.15 ]
 [ 0.7   -0.6   -0.3    0.2  ]
 [ 0.15  -0.2    0.15  -0.1  ]]
[[ 0.05  -0.4    0.05   0.3  ]
 [-0.525  1.2   -0.025 -0.15 ]
 [ 0.7   -0.6   -0.3    0.2  ]
 [ 0.15  -0.2    0.15  -0.1  ]]


## cholesky
* simetrica definida positiva

In [ ]:
# matriu simètrica i d[k, k] != 0

def cholesky(A, tol = 1.e-10):
    n = len(A)
    L = np.zeros([n,n])
    for k in range(0, n):
        if (abs(A[k,k]) < tol):
            raise ValueError("Element diagonal massa petit!")
        L[k,k] = A[k,k]
        for r in range(0, k):
            L[k,k] -= (L[k,r]**2)
        L[k,k] = (L[k,k]**(0.5))
        for i in range(k+1, n):
            L[i,k] = A[i,k]
            for r in range(0, k):
                L[i,k] -= (L[i,r]*L[k,r])
            L[i,k] /= L[k,k]
    return L

A = np.array([[5.,1.,1.,1.,1.],[1.,1.,0.,0.,0.],[1.,0.,1.,0.,0.],[1.,0.,0.,1.,0.],[1.,0.,0.,0.,1.]])
try:
    print("L:")
    L = cholesky(A)
    print(L)
    #print("comprovant:")
    #print(L@L.T)
except ValueError as e:
    print(e)

L:
[[ 2.23606798  0.          0.          0.          0.        ]
 [ 0.4472136   0.89442719  0.          0.          0.        ]
 [ 0.4472136  -0.2236068   0.8660254   0.          0.        ]
 [ 0.4472136  -0.2236068  -0.28867513  0.81649658  0.        ]
 [ 0.4472136  -0.2236068  -0.28867513 -0.40824829  0.70710678]]


In [ ]:
def inversa(L):
    n = len(L)
    invA = np.zeros((n, n))
    Id = np.eye(n)
    for k in range(0, n):
        b = Id[:,k]
        y = triL(L, b)
        invA[:,k] = triU(L.T,y)
    return invA

A = np.array([[5.,1.,1.,1.,1.],[1.,1.,0.,0.,0.],[1.,0.,1.,0.,0.],[1.,0.,0.,1.,0.],[1.,0.,0.,0.,1.]])
L = cholesky(A)

invA = inversa(L)
print("invA:")
print(invA)
#print("comprovant que doni identitat:")
#print(A@invA)
#A = np.array([[5.,1.,1.,1.,1.],[1.,1.,0.,0.,0.],[1.,0.,1.,0.,0.],[1.,0.,0.,1.,0.],[1.,0.,0.,0.,1.]])
#print(np.linalg.inv(A))

invA:
[[ 1. -1. -1. -1. -1.]
 [-1.  2.  1.  1.  1.]
 [-1.  1.  2.  1.  1.]
 [-1.  1.  1.  2.  1.]
 [-1.  1.  1.  1.  2.]]


#### per a matrius simètriques es pot fer factorització A = LDL.T
* en aquest cas els elements diagonals de D han de ser diferents de 0

## gram Schmidt mod
* Q ortonormal per columnes
* R triangular superior
* A ha de tenir rang màxim = les columnes o files siguin li

In [ ]:
def gram_schmidt(A, tol=1.e-10):
    m = len(A)
    n = len(A[0])
    Q = np.copy(A)
    R = np.zeros((n, n))

    for i in range(0, n):
        R[i, i] = np.linalg.norm(Q[:, i])
        if (abs(R[i,i]) < tol):
            raise ValueError("Element diagonal massa petit!")
        Q[:, i] /= R[i, i]
        for j in range(i+1, n):
            R[i, j] = np.dot(Q[:, i], Q[:, j])
            Q[:, j] -= np.dot(R[i, j], Q[:, i])

    return Q, R

A = np.array([[1., 0., 1.], [0., 0., 1.], [1., -2., 1.], [0., 1., 0.]])
Q, R = gram_schmidt(A)
try:
    Q, R = gram_schmidt(A)
    print("Q:")
    print(Q)
    print("R:")
    print(R)
    print()
    print(Q@R)
except ValueError as e:
    print(e)

Q:
[[ 7.07106781e-01  5.77350269e-01  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 7.07106781e-01 -5.77350269e-01  2.22044605e-16]
 [ 0.00000000e+00  5.77350269e-01  4.26983490e-32]]
R:
[[ 1.41421356e+00 -1.41421356e+00  1.41421356e+00]
 [ 0.00000000e+00  1.73205081e+00 -7.39557099e-32]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[ 1.00000000e+00 -8.61268352e-17  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]]


## normes

In [ ]:
def norma1(v):
    return np.sum(np.abs(v))

def norma2(v):
    ans = 0
    for i in range(0, len(v)):
        ans += v[i]*v[i]
    return(ans**0.5)

def normainf(v):
    return np.max(np.abs(v))

def normap(v, p):
    ans = 0
    for i in range(0, len(v)):
        ans += v[i]**p
    return(ans**(1/p))

def norma1Matricial(A):
    n = len(A)
    suma = 0
    mm = 0
    for j in range(n):
        for i in range(n):
            suma += abs(A[i][j])
        mm = max(mm, suma)
        suma = 0
    return mm

def normaInfMatricial(A):
    n = len(A)
    suma = 0
    mm = 0
    for j in range(n):
        for i in range(n):
            suma += abs(A[j][i])
        mm = max(mm, suma)
        suma = 0
    return mm

def normaFrobMatricial(A):
    n = len(A)
    suma = 0
    for j in range(n):
        for i in range(n):
            suma += abs(A[i][j])*abs(A[i][j])

    return np.sqrt(suma)


A = np.array([[1, -2, 3],
            [-4, 5, -6],
            [7, 8, 9]])

print(norma1Matricial(A))
print(normaInfMatricial(A))
print(normaFrobMatricial(A))

# funcions numpy
# print(np.linalg.norm(A, 1))
# print(np.linalg.norm(A, np.inf))
# nombre de condició: µ(A) = norma(A)*norma(inv(A))

18
24
16.881943016134134


## householder
* A ha de tenir rang màxim

In [ ]:
def matHouseholder(u):
    n = len(u)
    H = np.eye(n) - 2*u@u.T/(u.T@u)
    return H

def factHouseholder(A):
    n = len(A)
    Q = np.identity(n)

    for k in range(n):
        a2 = 0
        a1 = A[k:, k].copy()

        if (a1[0] > 0):
            a2 = -1 * np.linalg.norm(a1)
        else:
            a2 = np.linalg.norm(a1)

        ubar = a1
        ubar[0] -= a2
        ubar = np.reshape(ubar,(-1,1))

        H1 = matHouseholder(ubar)

        Haux = np.identity(n)
        Haux[k:, k:] = H1
        A = np.dot(Haux, A)
        Q = np.dot(Haux, Q)


    return Q.T, A

A = np.array([[1, -7, 0], [2, -20, 5], [2, 1, 1]], dtype = np.float64)
b = np.array([[-15, -27, 3]],dtype = np.float64).T

Q, R = factHouseholder(A)
print(Q)
print()
print(R)
print()
print(Q@R)

[[-0.33333333 -0.13333333  0.93333333]
 [-0.66666667 -0.66666667 -0.33333333]
 [-0.66666667  0.73333333 -0.13333333]]

[[-3.00000000e+00  1.50000000e+01 -4.00000000e+00]
 [ 4.44089210e-17  1.50000000e+01 -2.60000000e+00]
 [-3.10862447e-16  1.77635684e-16 -1.80000000e+00]]

[[ 1.00000000e+00 -7.00000000e+00 -8.18604443e-16]
 [ 2.00000000e+00 -2.00000000e+01  5.00000000e+00]
 [ 2.00000000e+00  1.00000000e+00  1.00000000e+00]]


In [ ]:
def matHouseholder(u):
    n = len(u)
    H = np.eye(n) - 2*u@u.T/(u.T@u)
    return H

def Householder(A, b):
    n = len(A)

    for k in range(n):
        a2 = 0
        a1 = A[k:, k].copy()

        if (a1[0] > 0):
            a2 = -1 * np.linalg.norm(a1)
        else:
            a2 = np.linalg.norm(a1)

        ubar = a1
        ubar[0] -= a2
        ubar = np.reshape(ubar,(-1,1))

        H1 = matHouseholder(ubar)

        Haux = np.identity(n)
        Haux[k:, k:] = H1

        ubar = ubar / np.linalg.norm(ubar)

        A = np.dot(Haux, A)
        b[k:] = b[k:]- ubar@(2*(ubar.T@b[k:]))

        #b = Haux@b

    return A, b

A = np.array([[1, -7, 0], [2, -20, 5], [2, 1, 1]], dtype = np.float64)
b = np.array([[-15, -27, 3]],dtype = np.float64).T

#print(np.linalg.solve(A, b)) # comprovació

R, b = Householder(A, b)
#print(R)
#print()
#print(b)
#print()
#print(Q@R)

# resolem el sistema
X = triU(R, b)
print(X)

[[-1.]
 [ 2.]
 [ 3.]]


## jacobi

In [ ]:
# resoldre sistemes lineals d'equacions, en  especial els que son edd
# tots els elements diagonals diferents de 0
# convergeix si A es edd, però pot convergir si no és edd

def jacobi(A, b, x, tol = 1.e-10, maxIter = 100):
    n = len(A)

    D = np.diag(np.diag(A))
    D_1 = np.diag(1 / np.diag(A))
    LU = np.tril(A, -1) + np.triu(A, 1)

    B = np.dot(-D_1, LU)
    C = np.dot(D_1, b)

    for i in range(maxIter):
        y = np.dot(B, x) + C
        if (norma2(y-x)/norma2(y) < tol):
            return y, i
        x = y

    return -1, -1

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([1.0, 0.0])
x = np.array([1.0, 0.5])
Y, it = jacobi(A, b, x)

print(Y)
print(it)

[ 0.6 -0.2]
27


## gauss - seidel

In [ ]:
# tots els elements diagonals han de ser diferents de 0
# El mètode de Gauss-Seidel és convergent si la matriu  𝐴  és edd,
# i pot convergir inclòs si aquesta condició no es satisfà.

def gaussseidel(A, b, x, tol = 1.e-10, maxIter = 100):
    n = len(A)

    y = np.zeros(n)
    for k in range(maxIter):
        for i in range(0, n):

            q = w = 0
            for j in range(i+1, n):
                q += A[i, j] * y[j]

            for j in range(0, i):
                w += A[i, j] * y[j]

            y[i] = (b[i] - w - q) / A[i, i]

        if (norma2(y-x)/norma2(y) < tol):
            return y, k

        x = y.copy()
    return -1, -1

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([1.0, 0.0])
x = np.array([1.0, 0.5])
y, it = gaussseidel(A, b, x)
print(y)
print(it)

[ 0.6 -0.2]
13


## w relaxació

In [ ]:
# w estar entre (0, 2)
# elements diagonals diferents de 0
def omegarelaxacio(A, b, x, tol = 1.e-10, maxIter = 100):
    n = len(A)

    y = x.copy()
    w = 1.1
    for k in range(maxIter):
        for i in range(0, n):

            q = t = 0
            for j in range(i+1, n):
                q += A[i, j] * y[j]

            for j in range(0, i):
                t += A[i, j] * y[j]

            y[i] = (1-w)*x[i] + (w / A[i, i])*(b[i] - t - q)

        if (norma2(y-x)/norma2(y) < tol):
            return y, k

        x = y.copy()

    return -1, -1

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([1.0, 0.0])
x = np.array([1.0, 0.5])
y, it = omegarelaxacio(A, b, x)
print(y, it)

[ 0.6 -0.2] 11


## mètode del gradient

In [ ]:
#matriu quadrada, simètrica i definida positiva

def Gradient(A, b, x, tol = 1.e-10, maxIter = 100):
    r = b-A@x
    k = 0
    it = 0
    while (np.linalg.norm(r) >= tol and it <= maxIter):
        alpha = (r.T@r)/(r.T@A@r)
        x += alpha*r
        r -= alpha*(A@r)
        k += 1
        it += 1
    if (it <= maxIter):
        return x, it
    else:
        return x, it

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([[1.0], [0.0]])
x = np.array([[1.0],[0.5]])

y, it = Gradient(A, b, x)
print(y, it)


[[ 0.6]
 [-0.2]] 6


## mètode del gradient conjugat
* matriu simètrica i def pos

In [ ]:
def GradientConjugat(A, b, x, tol = 1.e-10, maxIter = 100):
    r = b-A@x
    p = r.copy()
    k = 0
    gamma = r.T@r
    it = 0
    while (gamma >= tol*tol and it <= maxIter):
        y = A@p
        alpha = gamma/(p.T@y)
        x += alpha*p
        r -= alpha*y
        beta = (r.T@r)/gamma
        gamma = r.T@r
        p = r+beta*p
        k += 1
        it += 1

    if (it <= maxIter):
        return x, it
    else:
        return x, it

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([[1.0], [0.0]])
x = np.array([[1.0],[0.5]])

y, it = GradientConjugat(A, b, x)
print(y, it)

[[ 0.6]
 [-0.2]] 2


## mètode de la potència
* retorna el VAP de mòdul màxim i el VEP
* hi ha d'haver un VAP dominant i lambda2/lambda1 petit

In [ ]:
def pot(A,z0,tol=1.e-10,maxIter = 100):
    z0 = z0/np.linalg.norm(z0)
    sigma0 = 0

    for k in range(maxIter):
        z1 = A@z0
        sigma1 = z0.conj()@z1
        z1 = z1/np.linalg.norm(z1)

        if np.abs(sigma1-sigma0) < tol:
            return sigma1, z1, k+1

        z0 = z1
        sigma0 = sigma1

    return sigma1, z1, -maxIter

## Exemple:
C = np.array([[1,-3,3],[-1,1,1],[-1,-3,5]])
x = np.array([1,0,0])

l, v, iter = pot(C,x,tol = 1.e-12)
print(f"Resultat obtingut en {iter} iteracions:\nEl VAP dominant és {l} i el seu VEP associat és {v}")

Resultat obtingut en 95 iteracions:
El VAP dominant és 4.000000000000799 i el seu VEP associat és [ 7.07106781e-01 -2.82551760e-13  7.07106781e-01]


In [ ]:
def solucio_sistema(A, M, b):
    #M = np.array([[1, 1, 0], [2, 0, 2], [0, 3, 3]], dtype = np.float64)
    #A = factLU(M)
    n = len(A)
    ans = A

    #b = np.array([1,0,2], dtype = np.float64)
    Y = triL_uns_diagonal(A, b)
    X = triU(A, Y)

    return X

def potinv(A,z0,tol=1.e-10,maxIter = 100):
    LU = factLU(A)

    z0 = z0/np.linalg.norm(z0)
    sigma0 = 0

    for k in range(maxIter):
        z1 = solucio_sistema(LU, A, z0)
        sigma1 = z0.conj()@z1

        z1 = z1/np.linalg.norm(z1)

        if np.abs(sigma1-sigma0) < tol:
            return sigma1, z1, k+1

        z0 = z1
        sigma0 = sigma1

    return sigma1, z1, -maxIter


## Exemple:
C = np.array([[1,-3,3],[-1,1,1],[-1,-3,5]])
x = np.array([-1,0,0])

l, v, iter = potinv(C,x,tol = 1.e-12)
print(f"Resultat obtingut en {iter} iteracions:\nEl VAP més petit és {l} i el seu VEP associat és {v}")

Resultat obtingut en 41 iteracions:
El VAP més petit és 1.0000000000006068 i el seu VEP associat és [-0.57735027 -0.57735027 -0.57735027]


In [ ]:
def potdesp(A,z0,q,tol=1.e-10,maxIter = 100):
    n = len(A)
    M = A - q*np.eye(n)
    vap, vep, iter = pot(M,z0,tol=tol,maxIter = maxIter)
    return vap+q, vep, iter

In [ ]:
def potinvdesp(A,z0,q,tol=1.e-10,maxIter = 100):
    n = len(A)
    M = A - q*np.eye(n)
    vap, vep, iter = potinv(M,z0,tol=tol,maxIter = maxIter) # Aquí haureu de cridar la vostra funció
    return vap+q, vep, iter


In [ ]:
A = np.array([[-6, 2, 2, -14],[-2, -6, -2, 10],[2, 12, 8, -10], [0, -2, -2, 8]])
x = np.random.rand(4)

In [ ]:
# troba el vap més gran (no valor abs)

A = np.array([[-4, 0, 0], [0, 1, 0], [0, 0, -6]])
z0 = np.random.rand(3)
vap, vep, it = pot(A, z0)

ans = vap

if (vap < 0):
    v1, vep1, it1 = potdesp(A, z0, vap)
    ans = v1

print(ans)

0.9999999999977538


In [ ]:
# troba el vap més petit (no valor abs)

A = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 3]])
z0 = np.random.rand(3)
vap, vep, it = pot(A, z0)

ans = vap

if (vap > 0):
    v1, vep1, it1 = potdesp(A, z0, vap)
    ans = v1

print(ans)

1.000000000021107


In [ ]:
# troba el vap més proper a q (funciona molt malament)

A = np.array([[-2, 0, 0], [0, 1, 0], [0, 0, 4]])
q = -5
z0 = np.random.rand(3)
vap, vep, it = potinv(A-q*np.eye(3), z0)
print(vap)

0.11111111108231643


## DEFLACIÓ
* retorna vaps i veps
* la matriu ha de diagonalitzar, si es simètrica diagonalitza

In [ ]:
def matHouseholder(u):
    n = len(u)
    u = np.reshape(u,(-1,1))
    H = np.eye(n)- (2/(u.T@u))*u@u.T
    return H

def deflacio(A, tolPot = 1.e-12, maxIterPot = 500):
    # 0 Mida matriu
    n = len(A)

    if n > 1:
        # 1 Apliquem mètode potència:
        z0 = np.random.rand(n)
        vap, vep, iter = pot(A,z0,tol=tolPot,maxIter = maxIterPot)

        # 2. Calculem el vector per generar la matriu de Householder
        u = vep.copy()
        if u[0] >= 0:
            u[0] += 1.
        else:
            u[0] -= 1.

        # 3. Calculem la matriu de Householder
        H = matHouseholder(u)

        # 4. Fem deflació:
        Anew = H@A@H

        # 5. Repetim el procediment amb la submatriu (de moment passo dels VEPs):
        vaps, veps = deflacio(Anew[1:,1:],tolPot = tolPot, maxIterPot = maxIterPot)

        # 6. Recuperem els vaps, he d'afegir el vap calculat amb el mètode
        #    de la potència als vaps que m'ha donat la funció per la matriu Anew[1:,1:]
        vaps = np.append(vaps,vap)

        # 7. Recuperem VEPS (de moment no cal)
        V = np.zeros((n,n))
        V[1:,0:-1] = veps

        for i in range(n-2):
            if np.abs(vaps[i]-vap) < tolPot:
                alpha = 0
            else:
                alpha = (Anew[0, 1:]@veps[:,i]) / (vaps[i] - vap)

            V[0, i] = alpha

        V = H@V
        V[:, -1] = vep

        # Retornem vaps (i veps de moment no):
        return vaps, V
    else:
        vap = A[0]
        return vap, 1


# Matriu A per testejar:
A = np.random.rand(5,5)
A = (A+A.T)/2 # simètrica, per assegurar que isgui diagonalitzable

vaps, veps = np.linalg.eig(A)
# VAPs i VEPs
l1, l2 = deflacio(A)

# Retorno els vaps ordenats:
print(np.sort(vaps))
print(np.sort(l1))
# retorno els veps
print(veps)
print(l2) # per columnes

[-0.7379364  -0.14868142  0.65550512  0.86708767  2.72220489]
[-0.7379364  -0.14868142  0.65550512  0.86708767  2.72220489]
[[ 0.47513812  0.1127454  -0.67774263  0.54790181 -0.04472997]
 [ 0.36759421  0.20834907 -0.09409084 -0.53713955 -0.7239428 ]
 [ 0.51923156 -0.45486886  0.59215042  0.35863325 -0.21031637]
 [ 0.40672204 -0.50799803 -0.2564779  -0.52592828  0.48387365]
 [ 0.45176767  0.69203429  0.33968927 -0.07788678  0.44219833]]
[[-0.67774265 -0.54790194  0.11274472  0.04472986  0.47513812]
 [-0.09409082  0.53713927  0.20835057  0.72394259  0.36759418]
 [ 0.59215041 -0.35863266 -0.45486911  0.21031687  0.51923156]
 [-0.25647788  0.52592896 -0.50799786 -0.48387309  0.40672206]
 [ 0.33968928  0.07788585  0.69203391 -0.44219907  0.45176767]]


## rotació jacobi
* matrius simètriques

In [ ]:
def matriuQ(p, q, calpha, salpha, n):
    Q = np.eye(n, dtype=float)
    Q[p, p] = calpha
    Q[q, q] = calpha
    Q[p, q] = -salpha
    Q[q, p] = salpha
    return Q

def jacobiRotacio(A, tol=1.e-10, maxRot=1000):
    n = len(A)
    P = np.eye(n)

    for k in range(maxRot):
        p = q = 0
        maxval = 0

        for i in range(n):
            for j in range(i, n):
                if i == j:
                    continue
                if abs(A[i, j]) > maxval:
                    maxval = abs(A[i, j])
                    p = i
                    q = j

        eta = (A[p, p] - A[q, q]) / (2*A[p, q])

        if(eta < 0):
            t = -eta + np.sqrt(eta*eta + 1)
            Q = matriuQ(p, q, 1/np.sqrt(1+t*t), t*(1/np.sqrt(1+t*t)), n)
        else:
            t = -eta - np.sqrt(eta*eta+1)
            Q = matriuQ(p, q, 1/np.sqrt(1+t*t), t*(1/np.sqrt(1+t*t)), n)

        P = P@Q
        A = Q.T@A@Q

        flag = True
        for i in range(n):
            for j in range(i, n):
                if i == j:
                    continue
                if abs(A[i, j]) > tol:
                    flag = False
                    break

        if (flag):
            #return np.diag(A), P
            return np.diag(A), P

#################### PER TESTEJAR ####################

# Codi per testejar que funciona bé:
A = np.random.rand(10,10)
A = (A+A.T)/2 #Ara A és una matriu simètrica

# Funció de numpy per calcular els vaps i veps i perquè comproveu que teniu els mateixos resultats
vaps, veps = np.linalg.eig(A) # Retorna els vaps i una matriu amb els veps normalitzats
print(np.sort(vaps))
#print(veps)

print("||Id - P^T@P|| =", np.linalg.norm(np.eye(len(veps)) - veps.T@veps))

# Crideu la vostra funció:
vaps1, veps1 = jacobiRotacio(A) #veps per columnes
print(np.sort(vaps1))
#print()
#print(veps1)
print("||Id - P^T@P|| =", np.linalg.norm(np.eye(len(veps1)) - veps1.T@veps1))

[-1.11520317 -0.67126649 -0.57590425 -0.31281464 -0.0396688   0.03416855
  0.36470566  0.62704687  0.99594255  4.90689547]
||Id - P^T@P|| = 4.084813008545302e-15
[-1.11520317 -0.67126649 -0.57590425 -0.31281464 -0.0396688   0.03416855
  0.36470566  0.62704687  0.99594255  4.90689547]
||Id - P^T@P|| = 3.601315317106727e-15


## APUNTS:
* No hay ning ́un criterio general para saber qu ́e m ́etodo usar, pero en la pr ́actica se observa que el
m ́etodo directo es  ́util cuando la matriz es densa (pocos ceros) y su dimensi ́on es m ́as pequena que 100, y el m ́etodo iterativo va bien cuando la matriz es escasa (muchos ceros) y su dimensi ́on
es m ́as grande que 100.